// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBrand(arg1) {
  return window['go']['main']['App']['CreateBrand'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['main']['App']['CreateProduct'](arg1);
}

export function CreateVariant(arg1) {
  return window['go']['main']['App']['CreateVariant'](arg1);
}

export function DeleteBrand(arg1) {
  return window['go']['main']['App']['DeleteBrand'](arg1);
}

export function GetBrands() {
  return window['go']['main']['App']['GetBrands']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateBrand(arg1) {
  return window['go']['main']['App']['UpdateBrand'](arg1);
}
