// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateProduct(arg1:domain.Product):Promise<void>;

export function CreateVariant(arg1:domain.ItemVariant):Promise<void>;

export function GetProducts():Promise<Array<domain.Product>>;

export function Greet(arg1:string):Promise<string>;
