// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateBrand(arg1:domain.Brand):Promise<void>;

export function CreateCategory(arg1:domain.Category):Promise<void>;

export function CreateProduct(arg1:domain.Product):Promise<void>;

export function CreateSale(arg1:domain.Sale):Promise<domain.Sale>;

export function CreateVariant(arg1:domain.ItemVariant):Promise<void>;

export function DeleteBrand(arg1:number):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeleteVariant(arg1:number):Promise<void>;

export function GetBrands():Promise<Array<domain.Brand>>;

export function GetCategories():Promise<Array<domain.Category>>;

export function GetProducts():Promise<Array<domain.Product>>;

export function GetPurchases(arg1:number):Promise<Array<domain.Purchase>>;

export function GetSales(arg1:number):Promise<Array<domain.Sale>>;

export function GetSalesReport(arg1:string,arg2:number):Promise<Array<domain.ReportRow>>;

export function GetSettings():Promise<Record<string, string>>;

export function PickProductImage(arg1:number):Promise<string>;

export function RecordPurchase(arg1:domain.Purchase,arg2:number):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function UpdateBrand(arg1:domain.Brand):Promise<void>;

export function UpdateCategory(arg1:domain.Category):Promise<void>;

export function UpdateProduct(arg1:domain.Product):Promise<void>;

export function UpdateVariant(arg1:domain.ItemVariant):Promise<void>;
